### ISSUE TITLE
How to run with mono-i data?

### ISSUE THREAD

**Issue by Chanchanhan** [HyHuang1995/gmmloc#5]
Hello!
  Thanks for sharing your work!
  Tn order to study related issues of VIO couple with pre-bulilt We record our own data(mono image sequence and imu data) and want to test on gmmloc, but failed because gmm only support stereo format, can you help us with running this data with gmmloc?
  Thanks for your time!

**Comment by HyHuang1995** [comment]
Hi @Chanchanhan! Thank you for your interest. But I am sorry that currently, the code is not able to work with mono-inertial setup. Chaning the sensor setup to mono-inertial would require significant of workload.

**Comment by Chanchanhan** [comment]
> Hi @Chanchanhan! Thank you for your interest. But I am sorry that currently, the code is not able to work with mono-inertial setup. Chaning the sensor setup to mono-inertial would require significant of workload.

Thanks for your reply!
